import { memo, useMemo } from "react";

// 150+ real math expressions across calculus, linear algebra, physics,
// group theory, topology, statistics, and a handful of plain numerics.
const mathLines = [
  // Calculus
  "∫₀^∞ e^{-x²} dx = √π/2",
  "∑ₙ₌₁^∞ 1/n² = π²/6",
  "lim h→0 [f(x+h)-f(x)]/h",
  "d/dx[xⁿ] = nxⁿ⁻¹",
  "∫ sin²x dx = x/2 - sin(2x)/4",
  "∫₀^π sinx dx = 2",
  "∫₁^e 1/x dx = 1",
  "∑ 1/n! = e",
  "d(fg) = f·dg + g·df",
  "∫ eˣ dx = eˣ + C",
  "d/dx(ln x) = 1/x",
  "lim n→∞ (1+1/n)ⁿ = e",
  "∂²f/∂x∂y = ∂²f/∂y∂x",
  "∫₀^1 xⁿ dx = 1/(n+1)",
  "∮ F·dr = ∬ (∇×F)·dS",
  "∂L/∂q - d/dt(∂L/∂q̇) = 0",
  "f(z) = ∑aₙ(z-z₀)ⁿ",
  "F(s) = ∫₀^∞ f(t)e⁻ˢᵗ dt",
  "Γ(n+1) = n!",
  "∫∫∫ ρ dV = M",
  "f'(x₀) = lim Δy/Δx",
  "∂f/∂x = lim Δx→0",
  "∮ E·da = Q/ε₀",
  "W = ∫ F·ds",
  "∇f = (∂f/∂x, ∂f/∂y)",

  // Linear algebra
  "det(A-λI) = 0",
  "Tr(AB) = Tr(BA)",
  "‖u×v‖ = ‖u‖‖v‖sinθ",
  "Rⁿ → Rᵐ : T(αu+βv)",
  "dim(V) = rank(T) + null(T)",
  "σ(AB) \\ {0} = σ(BA) \\ {0}",
  "A⁻¹ = adj(A)/det(A)",
  "λ₁λ₂λ₃ = det(A)",
  "‖Ax‖ ≤ ‖A‖·‖x‖",
  "det(AB) = det(A)det(B)",
  "rank(A) ≤ min(m,n)",
  "Aᵀ A = I  ⇒  A ortogonal",
  "⟨u,v⟩ = ‖u‖‖v‖cosθ",
  "A = QR",
  "A = UΣVᵀ",
  "eigvals(A) ⊂ ℂ",
  "p(λ) = det(λI - A)",
  "(AB)ᵀ = BᵀAᵀ",

  // Physics — EM, mechanics, relativity, QM
  "∂²u/∂t² = c²∇²u",
  "∇×E = -∂B/∂t",
  "∇·B = 0",
  "∇·E = ρ/ε₀",
  "∇×B = μ₀J + μ₀ε₀∂E/∂t",
  "E = mc²",
  "Ric - ½Rg + Λg = 8πG/c⁴ T",
  "ds² = -c²dt² + a²(t)dr²",
  "p̂ = -iℏ∇",
  "Ĥψ = iℏ∂ψ/∂t",
  "⟨x|p⟩ = e^{ipx/ℏ}/√(2πℏ)",
  "[x̂, p̂] = iℏ",
  "ΔxΔp ≥ ℏ/2",
  "F = ma",
  "d²x/dt² + ω²x = 0",
  "T = 2π√(L/g)",
  "v² = u² + 2as",
  "λ = h/p",
  "E = hν",
  "R_μν = 0",
  "S = k_B ln Ω",
  "PV = nRT",
  "ΔG = ΔH - TΔS",
  "dS/dt ≥ 0",
  "F = G m₁m₂/r²",
  "p = mv",
  "L = r × p",
  "K = ½mv²",
  "U = -G m₁m₂/r",

  // Group theory & Galois
  "Gal(E/F) ≅ S₃",
  "[G:H] = |G|/|H|",
  "Ker(φ) ◁ G",
  "G/N ≅ im(φ)",
  "|G| = ∑ |G:Cᵢ|",
  "Aut(ℤ/nℤ) ≅ (ℤ/nℤ)*",
  "Sₙ generated by transpositions",
  "Aₙ ◁ Sₙ, [Sₙ:Aₙ]=2",
  "char(F) = 0 or p",
  "[E:F] = [E:K][K:F]",
  "Gal(ℚ(ζₙ)/ℚ) ≅ (ℤ/nℤ)*",
  "f solvable ⇔ Gal(f) solvable",

  // Number theory
  "ζ(s) = ∑ 1/nˢ",
  "∏ₚ (1-p⁻ˢ)⁻¹ = ζ(s)",
  "φ(n) = n∏(1-1/p)",
  "a ≡ b (mod n)",
  "gcd(a,b)·lcm(a,b) = |ab|",
  "∑ₖ₌₀ⁿ (-1)ᵏC(n,k) = 0",
  "(a+b)ⁿ = ∑ C(n,k)aⁿ⁻ᵏbᵏ",
  "aⁿ - bⁿ = (a-b)∑aᵏbⁿ⁻¹⁻ᵏ",
  "nCr = n!/r!(n-r)!",
  "π(x) ~ x/ln x",
  "aᵠ⁽ⁿ⁾ ≡ 1 (mod n)",
  "∑ μ(d) = [n=1]",

  // Topology / algebraic topology
  "χ(G) = ∑ (-1)ⁱ rank(Hᵢ)",
  "π₁(S¹) ≅ ℤ",
  "Hₙ(Sⁿ) ≅ ℤ",
  "χ(S²) = 2",
  "V - E + F = 2",

  // Statistics & information
  "P(A|B) = P(B|A)P(A)/P(B)",
  "H = -∑ pᵢ log₂ pᵢ",
  "E[X] = ∑ xᵢP(xᵢ)",
  "Var(X) = E[X²] - E[X]²",
  "f(x) = (1/σ√2π)e^{-(x-μ)²/2σ²}",
  "Cov(X,Y) = E[XY] - E[X]E[Y]",
  "ρ = Cov(X,Y)/σ_Xσ_Y",
  "χ² = ∑(O-E)²/E",
  "MLE: argmax_θ L(θ;x)",

  // Cubics / Cardano (stay close to project theme)
  "3x³ + 2x² - 7x + 1 = 0",
  "Δ = -4p³ - 27q²",
  "x₁ + x₂ + x₃ = -b/a",
  "x₁·x₂·x₃ = -d/a",
  "t³ + pt + q = 0",
  "u = ∛(-q/2 + √D)",
  "x = -b±√(b²-4ac)/2a",

  // Trig & basic identities
  "cos(α+β) = cosα·cosβ - sinα·sinβ",
  "sin(α+β) = sinα·cosβ + cosα·sinβ",
  "sin²θ + cos²θ = 1",
  "tan(π/4) = 1",
  "i² = -1",
  "ℝ ⊂ ℂ",
  "|z| = √(a²+b²)",
  "arg(z₁z₂) = arg(z₁)+arg(z₂)",
  "e^{iθ} = cosθ + isinθ",
  "eⁱᵖ + 1 = 0",
  "1 + tan²θ = sec²θ",
  "sin(2θ) = 2sinθcosθ",
  "cos(2θ) = 1 - 2sin²θ",

  // Geometry
  "A = πr²",
  "V = 4/3 πr³",
  "C = 2πr",
  "a² + b² = c²",
  "V_cyl = πr²h",
  "A_△ = ½·b·h",
  "A_trap = (a+b)h/2",

  // Series & sums
  "∑ₖ₌₁ⁿ k = n(n+1)/2",
  "∑ₖ₌₁ⁿ k² = n(n+1)(2n+1)/6",
  "∑ₖ₌₁ⁿ k³ = [n(n+1)/2]²",
  "Bₙ = ∑ S(n,k)",

  // Numeric flavor
  "12 × 47 = 564",
  "√2 ≈ 1.41421356…",
  "π ≈ 3.14159265…",
  "e ≈ 2.71828182…",
  "ln(ab) = ln(a) + ln(b)",
  "log₁₀(1000) = 3",
  "7! = 5040",
  "2¹⁰ = 1024",
  "∛27 = 3",
  "φ ≈ 1.61803398…",
  "γ ≈ 0.57721566…",
  "23 × 19 = 437",
  "97 is prime",
  "144 = 12²",
  "169 = 13²",
  "1729 = 1³+12³ = 9³+10³",
];

// Deterministic pseudo-random from index (no Math.random — SSR-safe)
const rng = (seed: number): number => {
  const x = Math.sin(seed * 127.1 + 311.7) * 43758.5453123;
  return x - Math.floor(x);
};

// Uses only opacity + transform — both compositor-threaded (no paint on main thread).
// clip-path was replaced because `clip-path: inset()` cannot be GPU-composited and
// caused full repaint every frame, creating main-thread contention with other animations.
const CHALK_KEYFRAMES = `
  @keyframes chalkLine {
    0%   { opacity: 0;    transform: translateX(6%); }
    8%   { opacity: .72; }
    24%  { transform: translateX(0%); }
    84%  { opacity: .72;  transform: translateX(0%); }
    96%  { opacity: 0;    transform: translateX(-4%); }
    100% { opacity: 0; }
  }

  @media (prefers-reduced-motion: reduce) {
    .chalk-row--animated {
      animation: none !important;
      opacity: .65 !important;
    }
  }
`;

interface MathBackgroundProps {
  /** Container opacity. If omitted, picks a sensible default per theme. */
  opacity?: number;
  /** Override ink color. If omitted, uses navy on light / chalk-white on dark. */
  color?: string;
  /** "light" = off-white background (navy ink). "dark" = navy background (chalk ink). */
  theme?: "light" | "dark";
  className?: string;
}

const ROW_COUNT = 46;
const TERMS_PER_ROW = 26;
const ANIMATE_EVERY = 11;

const makeLine = (seed: number, terms: number) =>
  Array.from({ length: terms }, (_, i) => mathLines[(seed * 7 + i * 11) % mathLines.length]).join("   ");

const MathBackground = memo(({ opacity, color, theme = "light", className = "" }: MathBackgroundProps) => {
  const rows = useMemo(
    () =>
      Array.from({ length: ROW_COUNT }, (_, i) => ({
        text: makeLine(i, TERMS_PER_ROW),
        shift: -22 - rng(i + 20) * 22,
        rotate: (rng(i + 40) - 0.5) * 1.1,
        sizeScale: 0.9 + rng(i + 60) * 0.18,
        alpha: 0.58 + rng(i + 80) * 0.24,
        animation:
          i % ANIMATE_EVERY === 0
            ? `chalkLine ${(18 + rng(i + 100) * 18).toFixed(1)}s -${(rng(i + 120) * 28).toFixed(1)}s infinite linear`
            : undefined,
      })),
    [],
  );

  const resolvedColor = color ?? (theme === "dark" ? "hsl(0, 0%, 90%)" : "hsl(215, 50%, 10%)");
  const resolvedOpacity = opacity ?? (theme === "dark" ? 0.06 : 0.045);

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: CHALK_KEYFRAMES }} />

      <div
        className={`pointer-events-none absolute inset-0 overflow-hidden select-none ${className}`}
        aria-hidden="true"
        style={{
          color: resolvedColor,
          opacity: resolvedOpacity,
          fontSize: "clamp(0.56rem, 0.85vw, 0.82rem)",
        }}
      >
        <div
          className="absolute inset-0 grid"
          style={{
            contain: "layout paint style",
            gridTemplateRows: `repeat(${ROW_COUNT}, minmax(0, 1fr))`,
          }}
        >
          {rows.map((row, i) => (
            <span
              key={i}
              className={`font-chalk whitespace-nowrap ${row.animation ? "chalk-row--animated" : ""}`}
              style={{
                alignSelf: "center",
                fontSize: `${row.sizeScale}em`,
                lineHeight: 1.05,
                opacity: row.alpha,
                transform: `translateX(${row.shift}%) rotate(${row.rotate}deg)`,
                transformOrigin: "left center",
                animation: row.animation,
                willChange: row.animation ? "opacity, transform" : undefined,
                textShadow: "0 0 1px currentColor",
              }}
            >
              {row.text}
            </span>
          ))}
        </div>
      </div>
    </>
  );
});

MathBackground.displayName = "MathBackground";

export default MathBackground;
